/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lineencoders;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.WindowConstants;

/**
 *
 * @author devan
 */
public class LineEncoders extends javax.swing.JFrame {

    /**
     * Creates new form LineEncoders
     */
    Graphics g;
    public LineEncoders() {
        initComponents();
        g=jPanel1.getGraphics();
        setSize(645,580);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(614, 480));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(614, 480));

        jButton1.setText("UniPolar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Polar NRZ-L");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Manchester");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Differential Manchester");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );

        textField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textField1.setText("Line Encoding Techniques");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        textField2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("Enter DataCode ");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Polar NRZ-I");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jTextField1, jTextField3});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton5, jButton6, jTextField1, jTextField3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Graphics2D g2d=(Graphics2D) g;
        g2d.setPaint(Color.BLACK);
        float[] dash1 = { 2f, 0f, 2f };
        BasicStroke bs1 = new BasicStroke(1, 
        BasicStroke.CAP_BUTT, 
        BasicStroke.JOIN_ROUND, 
        1.0f, 
        dash1,
        2f);
        g2d.setStroke(bs1);
        int temp=80;
        for(int i=0;i<8;i++){
            g2d.drawLine(temp, 40, temp, 260);
            temp+=40;
        }
        g2d.setStroke(new BasicStroke(4));
        g2d.drawLine(40,40,40,260);
        g2d.drawLine(40,150,380,150);
        
        String dataCode =jTextField1.getText();
        textField2.setText("Differntial Manchester");
        int x=40;
        int y=150;
        int prev=0;
        for(int i=0;i<dataCode.length();i++){
            if(i==0){
                if(dataCode.charAt(i)=='1'){
                    g2d.setPaint(Color.CYAN);
                    g2d.drawLine(x,50,x+20,50);
                    g2d.drawLine(x+20,50,x+20,250);
                    g2d.drawLine(x+20, 250, x+40, 250);
                    x+=40;
                    y=250;
                }
                else{
                    g2d.setPaint(Color.BLUE);
                    g2d.drawLine(x,250,x+20,250);
                    g2d.drawLine(x+20,250,x+20,50);
                    g2d.drawLine(x+20, 50, x+40, 50);
                    x+=40;
                    y=50;
                }
            }
            else{
                if(dataCode.charAt(i)=='1'){
                    g2d.setPaint(Color.BLUE);
                    g2d.drawLine(x,y,x+20,y);
                    int y1=y==250?50:250;
                    g2d.drawLine(x+20,y1,x+20,y);
                    g2d.drawLine(x+20, y1, x+40, y1);
                    x+=40;
                    y=y1;
                }
                else{
                    g2d.setPaint(Color.CYAN);
                    int y1=y==250?50:250;
                    g2d.drawLine(x,y,x,y1);
                    g2d.drawLine(x,y1,x+20,y1);
                    g2d.drawLine(x+20,y1,x+20,y);
                    g2d.drawLine(x+20, y, x+40, y);
                    x+=40;
                }
            }
            g2d.setPaint(Color.BLACK);
            g2d.drawString(dataCode.charAt(i)+"", x-25, 30);
        }           
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Graphics2D g2d=(Graphics2D) g;
        g2d.setPaint(Color.BLACK);
        float[] dash1 = { 2f, 0f, 2f };
        BasicStroke bs1 = new BasicStroke(1, 
        BasicStroke.CAP_BUTT, 
        BasicStroke.JOIN_ROUND, 
        1.0f, 
        dash1,
        2f);
        g2d.setStroke(bs1);
        int temp=80;
        for(int i=0;i<8;i++){
            g2d.drawLine(temp, 40, temp, 260);
            temp+=40;
        }

        g2d.setStroke(new BasicStroke(4));
        g2d.drawLine(40,40,40,260);
        g2d.drawLine(40,150,380,150);
        
        String dataCode =jTextField1.getText();
        textField2.setText("Manchester");
        int x=40;
        int y=150;
        int prev=0;
        for(int i=0;i<dataCode.length();i++){
            if(i==0){
                if(dataCode.charAt(i)=='1'){
                    g2d.setPaint(Color.BLUE);
                    g2d.drawLine(x,250,x+20,250);
                    g2d.drawLine(x+20,250,x+20,50);
                    g2d.drawLine(x+20, 50, x+40, 50);
                    x+=40;
                    y=50;
                }
                else{
                    g2d.setPaint(Color.CYAN);
                    g2d.drawLine(x,50,x+20,50);
                    g2d.drawLine(x+20,50,x+20,250);
                    g2d.drawLine(x+20, 250, x+40, 250);
                    x+=40;
                    y=250;
                }
            }
            else{
                if(dataCode.charAt(i)=='1'){
                    g2d.setPaint(Color.BLUE);
                    g2d.drawLine(x,y,x,250);
                    g2d.drawLine(x,250,x+20,250);
                    g2d.drawLine(x+20,250,x+20,50);
                    g2d.drawLine(x+20, 50, x+40, 50);
                    x+=40;
                    y=50;
                }
                else{
                    g2d.setPaint(Color.CYAN);
                     g2d.drawLine(x,y,x,50);
                    g2d.drawLine(x,50,x+20,50);
                    g2d.drawLine(x+20,50,x+20,250);
                    g2d.drawLine(x+20, 250, x+40, 250);
                    x+=40;
                    y=250;
                }
            }
            g2d.setPaint(Color.BLACK);
            g2d.drawString(dataCode.charAt(i)+"", x-25, 30);
        }           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Graphics2D g2d=(Graphics2D) g;
        g2d.setPaint(Color.BLACK);
        float[] dash1 = { 2f, 0f, 2f };
        BasicStroke bs1 = new BasicStroke(1, 
        BasicStroke.CAP_BUTT, 
        BasicStroke.JOIN_ROUND, 
        1.0f, 
        dash1,
        2f);
        g2d.setStroke(bs1);
        int temp=80;
        for(int i=0;i<8;i++){
            g2d.drawLine(temp, 40, temp, 260);
            temp+=40;
        }

        g2d.setStroke(new BasicStroke(4));
        g2d.drawLine(40,40,40,260);
        g2d.drawLine(40,150,380,150);
        
        String dataCode =jTextField1.getText();
        textField2.setText("UniPolar");
        int x=40;
        int y=150;
        for(int i=0;i<dataCode.length();i++){
            if(dataCode.charAt(i)=='1'){
                g2d.setPaint(Color.BLUE);
                g2d.drawLine(x,y,x,50);
                g2d.drawLine(x, 50, x+40, 50);
                x+=40;
                y=50;
            }
            else{
                g2d.setPaint(Color.CYAN);
                g2d.drawLine(x,y,x,150);
                g2d.drawLine(x, 150, x+40, 150);
                x+=40;
                y=150;
            }
            g2d.setPaint(Color.BLACK);
            g2d.drawString(dataCode.charAt(i)+"", x-25, 30);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Graphics2D g2d=(Graphics2D) g;
        g2d.setPaint(Color.BLACK);
        float[] dash1 = { 2f, 0f, 2f };
        BasicStroke bs1 = new BasicStroke(1, 
        BasicStroke.CAP_BUTT, 
        BasicStroke.JOIN_ROUND, 
        1.0f, 
        dash1,
        2f);
        g2d.setStroke(bs1);
        int temp=80;
        for(int i=0;i<8;i++){
            g2d.drawLine(temp, 40, temp, 260);
            temp+=40;
        }

        g2d.setStroke(new BasicStroke(4));
        g2d.drawLine(40,40,40,260);
        g2d.drawLine(40,150,380,150);
        
        String dataCode =jTextField1.getText();
        textField2.setText("Polar NRZ-L");
        int x=40;
        int y=150;
        for(int i=0;i<dataCode.length();i++){
            if(dataCode.charAt(i)=='1'){
                g2d.setPaint(Color.BLUE);
                g2d.drawLine(x,y,x,250);
                g2d.drawLine(x, 250, x+40, 250);
                x+=40;
                y=250;
            }
            else{
                g2d.setPaint(Color.CYAN);
                g2d.drawLine(x,y,x,50);
                g2d.drawLine(x, 50, x+40, 50);
                x+=40;
                y=50;
            }
            g2d.setPaint(Color.BLACK);
            g2d.drawString(dataCode.charAt(i)+"", x-25, 30);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Graphics2D g2d=(Graphics2D) g;
        textField2.setText("");
        g2d.setColor(Color.WHITE);
        g2d.fillRect(10,20,390,280);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Graphics2D g2d=(Graphics2D) g;
        g2d.setPaint(Color.BLACK);
        float[] dash1 = { 2f, 0f, 2f };
        BasicStroke bs1 = new BasicStroke(1, 
        BasicStroke.CAP_BUTT, 
        BasicStroke.JOIN_ROUND, 
        1.0f, 
        dash1,
        2f);
        g2d.setStroke(bs1);
        int temp=80;
        for(int i=0;i<8;i++){
            g2d.drawLine(temp, 40, temp, 260);
            temp+=40;
        }

        g2d.setStroke(new BasicStroke(4));
        g2d.drawLine(40,40,40,260);
        g2d.drawLine(40,150,380,150);
        
        String dataCode =jTextField1.getText();
        textField2.setText("Polar NRZ-I");
        int x=40;
        int y=50;
        for(int i=0;i<dataCode.length();i++){
            if(dataCode.charAt(i)=='1'){
                g2d.setPaint(Color.BLUE);
                int y1=y==50?250:50;
                g2d.drawLine(x,y,x,y1);
                g2d.drawLine(x, y1, x+40, y1);
                x+=40;
                y=y1;
            }
            else{
                g2d.setPaint(Color.CYAN);
                g2d.drawLine(x, y, x+40, y);
                x+=40;
            }
            g2d.setPaint(Color.BLACK);
            g2d.drawString(dataCode.charAt(i)+"", x-25, 30);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LineEncoders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LineEncoders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LineEncoders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LineEncoders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LineEncoders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
